// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBzXcPRtwQ1XXhD1-E6Rqv5YfOKiZyE8',
    appId: '1:812435260071:web:ab534bfefd972f05575182',
    messagingSenderId: '812435260071',
    projectId: 'worklance-a4c97',
    authDomain: 'worklance-a4c97.firebaseapp.com',
    storageBucket: 'worklance-a4c97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZafuXcJLScuMizuMPZn5P58hG0anwP0',
    appId: '1:812435260071:android:0fcdf6205066ddd0575182',
    messagingSenderId: '812435260071',
    projectId: 'worklance-a4c97',
    storageBucket: 'worklance-a4c97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbwx0_g0SYya38udEGrUaUIsZWd7aRCjs',
    appId: '1:812435260071:ios:d9238c901b4315ca575182',
    messagingSenderId: '812435260071',
    projectId: 'worklance-a4c97',
    storageBucket: 'worklance-a4c97.firebasestorage.app',
    iosBundleId: 'com.example.worklance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbwx0_g0SYya38udEGrUaUIsZWd7aRCjs',
    appId: '1:812435260071:ios:d9238c901b4315ca575182',
    messagingSenderId: '812435260071',
    projectId: 'worklance-a4c97',
    storageBucket: 'worklance-a4c97.firebasestorage.app',
    iosBundleId: 'com.example.worklance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYBzXcPRtwQ1XXhD1-E6Rqv5YfOKiZyE8',
    appId: '1:812435260071:web:1217779f2e56b138575182',
    messagingSenderId: '812435260071',
    projectId: 'worklance-a4c97',
    authDomain: 'worklance-a4c97.firebaseapp.com',
    storageBucket: 'worklance-a4c97.firebasestorage.app',
  );
}
